name: Publicacao e deploy do pacote

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - run: dotnet build --configuration Release

      - run: dotnet test

      - run: dotnet pack --configuration Release

      - run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s htts://api.nuget.org/v3/index.json
